name: EBAC-SHOP CI

on:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: UI

    steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 14
            cache: npm
            cache-dependency-path: '**/package-lock.json'

        - name: Install
          run: npm install
          working-directory: ./UI/

        - name: Cypress run
          run: npm t
          working-directory: ./UI/      
