name: EBAC-SHOP CI

on:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          working-directory: ./UI/
        - uses: actions/checkout@v3
        
        - name: Setup node
          working-directory: ./UI/
        - uses: actions/setup-node@v3
          with:
            node-version: 14
            cache: npm

        - name: Install
          run: npm install
          working-directory: ./UI/

        - name: Cypress run
          run: npm t
          working-directory: ./UI/

        - name: Rename Report
          run: mv ./UI/mochawesome-report/mochawesome.html ./UI/mochawesome-report/index.html

        - name: Publish Report
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./UI/mochawesome-report
      
